// Generated by CodiumAI

describe('getRandomInt', () => {

  function getRandomInt(max) {
    return Math.floor(Math.random() * max)
  }
  // Returns a random integer between 0 and max (exclusive) when max is a positive integer.
  it('should return a random integer between 0 and max (exclusive) when max is a positive integer', () => {
    const max = 10;
    const result = getRandomInt(max);
    expect(result).toBeGreaterThanOrEqual(0);
    expect(result).toBeLessThan(max);
  });

  // Returns 0 when max is 1.
  it('should return 0 when max is 1', () => {
    const max = 1;
    const result = getRandomInt(max);
    expect(result).toBe(0);
  });

  // Returns NaN when max is not a positive integer.
  it('should return NaN when max is not a positive integer', () => {
    const max = "abc";
    const result = getRandomInt(max);
    expect(result).toBeNaN();
  });

  // Returns NaN when max is 0.
  it('should return NaN when max is 0', () => {
    const max = 0;
    const result = getRandomInt(max);
    expect(result).toBe(0);
  });

  // Returns NaN when max is negative.
  it('should return NaN when max is negative', () => {
    const max = -10;
    const result = getRandomInt(max);
    expect(result).toBe(-1);
  });

  // Returns an integer when max is a floating-point number.
  it('should return an integer when max is a floating-point number', () => {
    const max = 10.5;
    const result = getRandomInt(max);
    expect(Number.isInteger(result)).toBe(true);
  });

});
